version: "3.8"

services:
  rentalpro:
    image: ghcr.io/mattheuscamargo/rental:latest
    container_name: rentalpro_app
    restart: always
    environment:
      # Essas variávies podem ser sobrescritas no Portainer
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
      - JWT_SECRET=rentalpro-chave-secreta-2024 # Mude esta chave!
      - NEXTAUTH_SECRET=rentalpro-nextauth-secret # Mude esta chave!
      - NEXTAUTH_URL=https://reservasita.com.br
    volumes:
      - rental_data:/app/data
    networks:
      - Lurds
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rentalpro.rule=Host(`reservasita.com.br`)"
        - "traefik.http.routers.rentalpro.service=rentalpro"
        - "traefik.http.routers.rentalpro.entrypoints=websecure"
        - "traefik.http.routers.rentalpro.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.rentalpro.tls=true"
        - "traefik.http.services.rentalpro.loadbalancer.server.port=3000"

volumes:
  rental_data:

networks:
  Lurds:
    external: true
