version: "3.8"

services:
  rentalpro:
    image: ghcr.io/trissutto/rentalpro:latest
    container_name: rentalpro_app
    restart: always
    environment:
      # Essas variávies podem ser sobrescritas no Portainer
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/dev.db
      - JWT_SECRET=rentalpro-chave-secreta-2024 # Mude esta chave!
      - NEXTAUTH_SECRET=rentalpro-nextauth-secret # Mude esta chave!
      - NEXTAUTH_URL=https://reservasita.com.br
      - NEXT_PUBLIC_BASE_URL=https://reservasita.com.br
      # Força o Prisma a usar o binário correto para Alpine Linux
      - PRISMA_QUERY_ENGINE_LIBRARY=/app/node_modules/.prisma/client/libquery_engine-linux-musl-openssl-3.0.x.so.node
    volumes:
      - rental_data:/app/prisma
    networks:
      - Lurds
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rentalpro.rule=Host(`reservasita.com.br`)"
        - "traefik.http.routers.rentalpro.service=rentalpro"
        - "traefik.http.routers.rentalpro.entrypoints=websecure"
        - "traefik.http.routers.rentalpro.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.rentalpro.tls=true"
        - "traefik.http.services.rentalpro.loadbalancer.server.port=3000"

volumes:
  rental_data:

networks:
  Lurds:
    external: true